name: tests-orders

on:
  push:
    paths:
      - '23_CI_CD/app/orders/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd 23_CI_CD/app/orders && npm install && npm run test:ci
